---
title: "crescynt test"
author: "Josh Levy"
date: "3/12/2018"
output: html_document
---

## Learning ggplot2 
```{r}
library("ggplot2", lib.loc="~/Library/R/3.2/library")
library("ggthemes", lib.loc="~/Library/R/3.2/library")
```



```{r}
mygraph <- ggplot(data= mpg, aes(x = cyl, y = cty)) +
  geom_point(alpha = 0.4)
mygraph
```


```{r}
ggplot(data= mpg, aes(x = cyl, y = cty, color = class)) +
  geom_point()
```

Make scatter of 'hwy' vs 'cty' with diff sized points for class and different colors for fuel

```{r}
ggplot(data= mpg, aes(x = hwy, y = cty, size = class, color = fl)) +
  geom_point()
```

Make all points blue
```{r}
ggplot(data= mpg, aes(x = displ, y = hwy)) +
     geom_point (alpha = 0.4, color = 'blue')
```

faceting and theme changes 

```{r}
ggplot(data= mpg, aes(x = displ, y = hwy, color = class)) +
  geom_point () + 
  facet_grid(~ cyl, scales = "free") +
  theme_bw()
```

```{r}
ggplot(mpg, aes(x = drv, y = hwy)) +
  geom_boxplot() #or jitterplot
```

lables and linar lines

```{r}
ggplot(mpg, aes(x = displ, y = hwy)) +
  geom_smooth(method = 'lm') +
  geom_point() +
labs(title = "relationship between engine size and hwy efficiency (mpg)",
     x = "Displacement",
     y = "Milage (mpg)")
```

bar charts

```{r}
ggplot(mpg, aes(x = fl, fill = class)) +
  geom_bar(position = "fill") 
```




